data: 
    mask: '/Users/mstrzys/Documents/Sandbox/Template_bkg_test/20150625/20*.root'
    cuts: '(MHillas_1.fSize>100) & (MHadronness.fHadronness < 0.5) & (MStereoPar.fValid == 1)'

# mode: 'stacked_wobble'
mode: 'runwise_exclusion'
    
output:
    directory: '/Users/mstrzys/Documents/Sandbox/Template_bkg_test/20150625/'
    prefix: ''
    overwrite: True

run_matching:
    time_delta: '0.2 hour'
    pointing_delta: '2 deg'

binning:
    mode: 'rectangular'
    extension:
    x: 
        min: '-1.5 deg'
        max: '1.5 deg'
        nbins: 10
    y: 
        min: '-1.5 deg'
        max: '1.5 deg'
        nbins: 10
    energy:
        min: '100 GeV'
        max: '10 TeV'
        nbins: 1

exclusion_regions:
#    type: list
#    - {type: 'circle', x: 83.633080, y: 22.014500, rad: 0.2, unit: 'deg', frame: 'icrs'}
    - 'icrs; circle(83.633080, 22.014500, 0.2d)'
    - 'icrs; circle(83.133080, 22.414500, 0.2d)'

# run_matching: {val: 1, unit: 'arcmin'}
